In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV

In [2]:
train_df = pd.read_csv('../../data/data_base/ResultTrain_NonFixedData.csv')
test_df = pd.read_csv('../../data/data_base/ResultTest_NonFixedData.csv')

In [3]:
X_train = train_df.drop(['Concentration','Photo Name'], axis=1)
y_train = train_df[train_df.columns[1]].astype('int')

In [4]:
X_test = test_df.drop(['Concentration', 'Photo Name'], axis=1)
y_test = test_df[test_df.columns[1]].astype('int')

In [11]:
import xgboost as xgb

seed = 0

In [14]:
xgbc = xgb.XGBClassifier(
    seed = seed,
    use_label_encodeer = False,
    eval_metric = "merror"
)

In [19]:
xgboost_params = {
    "learning_rate": [0.001, 0.01, 0.05, 0.1, 0.3],
    "max_depth": [1,2,3,5,7,9, 12],
    "n_estimators": [10, 20, 50, 100, 150, 180, 300],
    "gamma": [1, 2, 4, 7, 9],
    "reg_alpha": [40, 60, 80, 120, 160, 180],
    "reg_lamda": [0.0001, 0.001, 0.01, 0.1, 0.3, 0.5, 0.7, 0.9],
    "colsample_bytree": [0.6, 0.7, 0.8, 0.9],
    "min_child_weight": [0.001, 0.01, 0.1, 1, 3, 5, 7, 9]
}

In [16]:
xgbc.fit(X_train, y_train)

[17:14:51] WARNING: ../src/learner.cc:767: 
Parameters: { "use_label_encodeer" } are not used.



XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='merror',
              feature_types=None, gamma=None, gpu_id=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, objective='multi:softprob',
              predictor=None, ...)

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = xgbc.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[382  15   6  16  55  18   8]
 [131 333  22   3   4   3   4]
 [  8  27 431   3  13  16   2]
 [ 11 230   7 140   7  45  60]
 [ 18  18  75  27 218  86  58]
 [  5  10  12   8  15 267 183]
 [ 11   2  96  32 130 149  80]]


0.5288571428571428